import numpy as np
import matplotlib.pyplot as plt
t1 = np.genfromtxt("1.txt", delimiter = " ")
t2 = np.genfromtxt("2.txt", delimiter = " ")
t3 = np.genfromtxt("3.txt", delimiter = " ")
t4 = np.genfromtxt("4.txt", delimiter = " ")
t5 = np.genfromtxt("5.txt", delimiter = " ")
t6 = np.genfromtxt("6.txt", delimiter = " ")
t7 = np.genfromtxt("7.txt", delimiter = " ")
t8 = np.genfromtxt("8.txt", delimiter = " ")
t9 = np.genfromtxt("9.txt", delimiter = " ")
t10 = np.genfromtxt("10.txt", delimiter = " ")
plt.plot(t1[:, 0],t1[:, 1], '-k.')
plt.plot(t2[:, 0],t2[:, 1], '-k.')
plt.plot(t3[:, 0],t3[:, 1], '-k.')
plt.plot(t4[:, 0],t4[:, 1], '-k.')
plt.plot(t5[:, 0],t5[:, 1], '-k.')
plt.plot(t6[:, 0],t6[:, 1], '-k.')
plt.plot(t7[:, 0],t7[:, 1], '-k.')
plt.plot(t8[:, 0],t8[:, 1], '-k.')
plt.plot(t9[:, 0],t9[:, 1], '-k.')
plt.plot(t10[:, 0],t10[:, 1], '-k.')
plt.show()